# This file tells PyScript what to load
# All files are Unicode Version 17 (& all Emoji v17).
packages = [
  "pyodide-http"
]

# This tells PyScript to pre-load your data files
[[fetch]]
files = [
    "Blocks.txt", 
    "DerivedAge.txt", 
    "IdentifierType.txt",
    "IdentifierStatus.txt",
    "intentional.txt",
    "confusables.txt", 
    "StandardizedVariants.txt",
    "ScriptExtensions.txt",
    "LineBreak.txt",
    "PropList.txt",
    "DerivedCoreProperties.txt",
    "Scripts.txt",
    "emoji-variation-sequences.txt",
    "WordBreakProperty.txt",
    "SentenceBreakProperty.txt",
    "GraphemeBreakProperty.txt",
    "DoNotEmit.txt",
    "DerivedCombiningClass.txt",
    "DerivedDecompositionType.txt",
    "DerivedBinaryProperties.txt",
    "DerivedNumericType.txt",
    "EastAsianWidth.txt",
    "VerticalOrientation.txt",
    "BidiBrackets.txt",
    "BidiMirroring.txt",
    "DerivedNormalizationProps.txt",
    "CompositionExclusions.txt",
    "emoji-sequences.txt",
    "emoji-zwj-sequences.txt",
    "emoji-data.txt",
    "emoji-test.txt",
    "inverse_confusables.json",
    "ascii_confusables.json",
    "IdnaMappingTable.txt",
    "Idna2008.txt"
]
