# This file tells PyScript what to load
packages = [
  "pyodide-http"
]

# This tells PyScript to pre-load your data files
[[fetch]]
files = [
    "Blocks.txt", 
    "DerivedAge.txt", 
    "IdentifierType.txt", 
    "confusables.txt", 
    "StandardizedVariants.txt",
    "ScriptExtensions.txt",
    "LineBreak.txt",
    "PropList.txt",
    "DerivedCoreProperties.txt",
    "Scripts.txt",
    "emoji-variation-sequences.txt"
]
